<a href="https://colab.research.google.com/github/shearere2/Miscellaneous/blob/main/Country_Extremes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [55]:
import pandas as pd
df = pd.read_csv('country_extremes.csv')

In [56]:
def floatify(c):
  c = c.replace(',', '')
  if c == 'sea level':
    return 0.0
  if c[0] == '−':
    return -float(c[1:-2])
  return float(c[:-2])

In [57]:
df['Minimum elevation'] = df['Minimum elevation'].apply(floatify)
df['Maximum elevation'] = df['Maximum elevation'].apply(floatify)
df['Elevation span'] = df['Elevation span'].apply(floatify)
df = df.rename(columns={'Country or region':'region', 'Continent':'continent',
                        'Highest point':'high_point', 'Maximum elevation':'max_elev_meters',
                        'Lowest point':'low_point', 'Minimum elevation':'min_elev_meters',
                        'Elevation span':'elev_span_meters'})

In [58]:
countries = pd.read_csv('countries of the world.csv')

In [59]:
countries['area_sq_km'] = countries['Area (sq. mi.)'].apply(lambda x: float(x)*2.59)

In [60]:
countries = countries.rename(columns={'Country':'region'})
countries['region'] = countries['region'].apply(lambda x: x.strip())
df['region'] = df['region'].apply(lambda x: x.strip('\xa0'))
df = df.merge(countries[['region', 'area_sq_km', 'Population']], on='region')

In [62]:
df['hilly_index'] = df['elev_span_meters']/df['area_sq_km']

In [64]:
df.sort_values(by='hilly_index')

,region,continent,high_point,max_elev_meters,low_point,min_elev_meters,elev_span_meters,area_sq_km,Population,hilly_index
10,Australia,Oceania,Mount Kosciuszko[d],2228.0,Lake Eyre,-15.0,2243.0,19908941.50,20264082,0.000113
147,Russia,Asia,Mount Elbrus[al],5642.0,Caspian Sea[am],-28.0,5670.0,44224768.00,142893540,0.000128
24,Brazil,America,Pico da Neblina,2995.0,Atlantic Ocean,0.0,2995.0,22045989.35,188078227,0.000136
31,Canada,America,Mount Logan[e],5959.0,North Atlantic Ocean,0.0,5959.0,25860295.30,33098932,0.000230
184,United States,America,Denali[av][aw][ax],6190.5,Badwater Basin[ay],-85.5,6276.0,24945377.80,298444215,0.000252
...,...,...,...,...,...,...,...,...,...,...
122,Montserrat,America,Chances Peak,915.0,Caribbean Sea,0.0,915.0,264.18,9439,3.463548
152,San Marino,Europe,Monte Titano,739.0,Ausa River,55.0,684.0,157.99,29251,4.329388
104,Liechtenstein,Europe,Grauspitz,2599.0,Rhine,430.0,2169.0,414.40,33987,5.234073
65,Gibraltar,Europe,Rock of Gibraltar,426.0,Strait of Gibraltar,0.0,426.0,18.13,27928,23.496966
120,Monaco,Europe,along Chemin des Révoires on Mont Agel,161.0,Mediterranean Sea,0.0,161.0,5.18,32543,31.081081